"""study_packs add transcript fields

Revision ID: 2837d8b91cde
Revises: 68c1d33aa189
Create Date: 2026-01-23 11:46:23.053868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2837d8b91cde'
down_revision: Union[str, None] = '68c1d33aa189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_packs', sa.Column('source_id', sa.String(length=64), nullable=True))
    op.add_column('study_packs', sa.Column('language', sa.String(length=16), nullable=True))
    op.add_column('study_packs', sa.Column('meta_json', sa.Text(), nullable=True))
    op.add_column('study_packs', sa.Column('transcript_json', sa.Text(), nullable=True))
    op.add_column('study_packs', sa.Column('transcript_text', sa.Text(), nullable=True))
    op.add_column('study_packs', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('study_packs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('study_packs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_study_packs_source_id'), 'study_packs', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_packs_source_id'), table_name='study_packs')
    op.drop_column('study_packs', 'updated_at')
    op.drop_column('study_packs', 'created_at')
    op.drop_column('study_packs', 'error')
    op.drop_column('study_packs', 'transcript_text')
    op.drop_column('study_packs', 'transcript_json')
    op.drop_column('study_packs', 'meta_json')
    op.drop_column('study_packs', 'language')
    op.drop_column('study_packs', 'source_id')
    # ### end Alembic commands ###
